FROM public.ecr.aws/amazonlinux/amazonlinux:2023

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="~/.cargo/bin:${PATH}"

RUN ~/.cargo/bin/rustup update \
    && ~/.cargo/bin/rustup target add aarch64-unknown-linux-gnu

RUN rustup default stable

# Install required build dependencies
RUN dnf install -y gcc openssl-devel python3-pip util-linux && \
    pip3 install setuptools && \
    dnf clean all

ENV CRYPTEIA_BUILD_OS=amzn
ENV CRYPTEIA_BUILD_TARGET=aarch64-unknown-linux-gnu
