FROM public.ecr.aws/lambda/provided:al2023

COPY build/crypteia-amzn /opt/extensions/crypteia
COPY build/libcrypteia-amzn.so /opt/lib/libcrypteia.so

ENV CRYPTEIA_BUILD_OS=amzn
ENV SKIP_CARGO_TEST=1

ENV EXISTING=existingvalue
ENV LD_PRELOAD=/opt/lib/libcrypteia.so

# For assert.sh support
RUN dnf install -y util-linux
RUN dnf clean all
