FROM ubuntu:focal

RUN apt update && \
    apt install -y curl && \
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

# cargo 1.61.0 (a028ae4 2022-04-29)
# rustup 1.24.3 (ce5817a94 2021-05-31)
# rustc 1.61.0 (fe5b13d68 2022-05-18)
