FROM ubuntu:22.04

ENV SHELL=/bin/sh

RUN apt-get update && apt-get install -y software-properties-common && add-apt-repository ppa:deadsnakes/ppa && apt-get update
RUN apt-get install -y --no-install-recommends \
      ca-certificates \
      curl \
      libffi-dev \
      python2.7 \
      python2.7-dev \
    && update-alternatives --install /usr/bin/python python /usr/bin/python2.7 2

RUN curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py \
    && python get-pip.py \
    && pip install --upgrade pip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY ./package/opt /opt

ENV CRYPTEIA_BUILD_OS=debian
ENV SKIP_CARGO_TEST=1

ENV EXISTING=existingvalue
ENV LD_PRELOAD=/opt/lib/libcrypteia.so
ENV PYTHONPATH=/opt/crypteia/python
