FROM ubuntu:20.04

ENV SHELL=/bin/sh

RUN apt update \
    && apt-get install -y curl \
    && apt-get install -y python2.7 python2.7-dev \
    && update-alternatives --install /usr/bin/python python /usr/bin/python2.7 2

RUN curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py \
    && python get-pip.py \
    && pip install --upgrade pip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY build/crypteia-debian /opt/extensions/crypteia
COPY build/libcrypteia-debian.so /opt/lib/libcrypteia.so
COPY package/opt/crypteia /opt/crypteia

ENV CRYPTEIA_BUILD_OS=debian
ENV SKIP_CARGO_TEST=1

ENV EXISTING=existingvalue
ENV LD_PRELOAD=/opt/lib/libcrypteia.so
ENV PYTHONPATH=/opt/crypteia/python
