FROM public.ecr.aws/sam/build-nodejs18.x:latest-arm64

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="~/.cargo/bin:${PATH}"

RUN ~/.cargo/bin/rustup update \
    && ~/.cargo/bin/rustup target add aarch64-unknown-linux-gnu

ENV BUILD_OS=amzn
ENV BUILD_TARGET=aarch64-unknown-linux-gnu
