#!/bin/sh
set -e

echo "== [amzn/Dockerfile] sam/build building... =="
docker build --tag crypteia-lambda-nodejs --file amzn/Dockerfile .

echo "== [amzn/Dockerfile] sam/build bin/setup =="
docker run \
  --rm \
  --user root \
  --entrypoint "./bin/setup" \
  --volume "${PWD}:/var/task" \
  crypteia-lambda-nodejs
