#!/bin/sh
set -e

echo "== [amzn/Dockerfile] bin/test =="
docker run \
  --rm \
  --user root \
  --entrypoint "./test/libcrypteia.sh" \
  --volume "${PWD}:/var/task" \
  --env TEST_LANG=node \
  crypteia-lambda-nodejs

echo "== [amzn/Dockerfile-test] bin/test =="
docker run \
  --rm \
  --user root \
  --entrypoint "./test/libcrypteia.sh" \
  --volume "${PWD}:/var/task" \
  --env TEST_LANG=node \
  crypteia-lambda-nodejs-test
