#!/bin/sh
set -e

echo "== [amzn/Dockerfile] sam/build bin/test =="
docker run \
  --rm \
  --user root \
  --entrypoint "./test/libcrypteia.sh" \
  --volume "${PWD}:/var/task" \
  --env TEST_LANG=node \
  crypteia-lambda-nodejs

echo "== [amzn/Dockerfile-test] lambda/runtime building... =="
docker build --tag crypteia-lambda-nodejs-test --file amzn/Dockerfile-test .

echo "== [amzn/Dockerfile-test] lambda/runtime bin/test =="
docker run \
  --rm \
  --user root \
  --entrypoint "./test/libcrypteia.sh" \
  --volume "${PWD}:/var/task" \
  --env TEST_LANG=node \
  crypteia-lambda-nodejs-test
