#!/bin/sh
set -e

if [ -z "${CRYPTEIA_VERSION}" ]; then
  echo "CRYPTEIA_VERSION is not set"
  exit 1
fi

CRYPTEIA_VERSION_MAJOR=$(echo "${CRYPTEIA_VERSION}" | cut -d. -f1)

docker login ghcr.io -u "cink-continuous-integration" -p $DOCKER_LOGIN_PAT

./amzn/setup
BASE_NAME_AMD64="ghcr.io/rails-lambda/crypteia-extension-amzn-amd64"
docker build \
  --platform linux/amd64 \
  --tag "${BASE_NAME_AMD64}:${CRYPTEIA_VERSION_MAJOR}" \
  --tag "${BASE_NAME_AMD64}:${CRYPTEIA_VERSION}" \
  --tag "${BASE_NAME_AMD64}:latest" \
  --file package/Dockerfile .
docker push "${BASE_NAME_AMD64}:${CRYPTEIA_VERSION_MAJOR}"
docker push "${BASE_NAME_AMD64}:${CRYPTEIA_VERSION}"
docker push "${BASE_NAME_AMD64}:latest"

./amzn/setup-arm64
BASE_NAME_ARM64="ghcr.io/rails-lambda/crypteia-extension-amzn-arm64"
docker build \
  --platform linux/arm64 \
  --tag "${BASE_NAME_ARM64}:${CRYPTEIA_VERSION_MAJOR}" \
  --tag "${BASE_NAME_ARM64}:${CRYPTEIA_VERSION}" \
  --tag "${BASE_NAME_ARM64}:latest" \
  --file package/Dockerfile .
docker push "${BASE_NAME_ARM64}:${CRYPTEIA_VERSION_MAJOR}"
docker push "${BASE_NAME_ARM64}:${CRYPTEIA_VERSION}"
docker push "${BASE_NAME_ARM64}:latest"

docker manifest create \
  "ghcr.io/rails-lambda/crypteia-extension-amzn:${CRYPTEIA_VERSION}" \
  --amend "${BASE_NAME_AMD64}:${CRYPTEIA_VERSION}" \
  --amend "${BASE_NAME_ARM64}:${CRYPTEIA_VERSION}"
docker manifest push "ghcr.io/rails-lambda/crypteia-extension-amzn:${CRYPTEIA_VERSION}"

docker manifest create \
  "ghcr.io/rails-lambda/crypteia-extension-amzn:${CRYPTEIA_VERSION}" \
  --amend "${BASE_NAME_AMD64}:${CRYPTEIA_VERSION}" \
  --amend "${BASE_NAME_ARM64}:${CRYPTEIA_VERSION}"
docker manifest push "ghcr.io/rails-lambda/crypteia-extension-amzn:${CRYPTEIA_VERSION}"

docker manifest create \
  "ghcr.io/rails-lambda/crypteia-extension-amzn:latest" \
  --amend "${BASE_NAME_AMD64}:latest" \
  --amend "${BASE_NAME_ARM64}:latest"
docker manifest push "ghcr.io/rails-lambda/crypteia-extension-amzn:latest"
