#!/bin/sh
set -e

if [ -z "${S3_BUCKET_NAME}" ]; then
  echo "S3_BUCKET_NAME is not set"
  exit 1
fi

cd ./package/opt
zip -r package.zip .
mv package.zip ..
cd ..

sam package \
  --template-file "template.yml" \
  --output-template-file "packaged.yaml" \
  --s3-bucket "${S3_BUCKET_NAME}"

sam deploy \
  --template-file "packaged.yaml" \
  --stack-name "crypteia-layer" \
  --capabilities CAPABILITY_IAM
