#!/bin/sh
set -e

if [ -z "${CRYPTEIA_VERSION}" ]; then
  echo "CRYPTEIA_VERSION is not set"
  exit 1
fi

echo "== [Lambda Extension Images] building... =="

docker build \
  --tag "ghcr.io/customink/crypteia-extension-amzn:${CRYPTEIA_VERSION}" \
  --file package/Dockerfile-amzn .

docker build \
  --tag "ghcr.io/customink/crypteia-extension-debian:${CRYPTEIA_VERSION}" \
  --file package/Dockerfile-debian .

echo "== [Lambda Extension Images] pushes... =="

docker push "ghcr.io/customink/crypteia-extension-amzn:${CRYPTEIA_VERSION}"

docker push "ghcr.io/customink/crypteia-extension-debian:${CRYPTEIA_VERSION}"
