#!/bin/sh
set -e

if [ -z "${CRYPTEIA_VERSION}" ]; then
  echo "CRYPTEIA_VERSION is not set"
  exit 1
fi

docker login ghcr.io -u "cink-continuous-integration" -p $DOCKER_LOGIN_PAT

./bin/setup

docker build \
  --tag "ghcr.io/customink/crypteia-extension-debian-amd64:${CRYPTEIA_VERSION}" \
  --file package/Dockerfile .
docker push "ghcr.io/customink/crypteia-extension-debian-amd64:${CRYPTEIA_VERSION}"

./debian/setup-arm64

docker build \
  --tag "ghcr.io/customink/crypteia-extension-debian-arm64:${CRYPTEIA_VERSION}" \
  --file package/Dockerfile .
docker push "ghcr.io/customink/crypteia-extension-debian-arm64:${CRYPTEIA_VERSION}"

docker manifest create \
  "ghcr.io/customink/crypteia-extension-debian:${CRYPTEIA_VERSION}" \
  --amend "ghcr.io/customink/crypteia-extension-debian-amd64:${CRYPTEIA_VERSION}" \
  --amend "ghcr.io/customink/crypteia-extension-debian-arm64:${CRYPTEIA_VERSION}"

docker manifest push "ghcr.io/customink/crypteia-extension-debian:${CRYPTEIA_VERSION}"
