#!/bin/sh
set -e

if [ -z "${CRYPTEIA_VERSION}" ]; then
  echo "CRYPTEIA_VERSION is not set"
  exit 1
fi

CRYPTEIA_VERSION_MAJOR=$(echo "${CRYPTEIA_VERSION}" | cut -d. -f1)

docker login ghcr.io -u "metaskills" -p $DOCKER_LOGIN_PAT

./bin/setup
BASE_NAME_AMD64="ghcr.io/rails-lambda/crypteia-extension-debian-amd64"
docker build \
  --platform linux/amd64 \
  --tag "${BASE_NAME_AMD64}:${CRYPTEIA_VERSION_MAJOR}" \
  --tag "${BASE_NAME_AMD64}:${CRYPTEIA_VERSION}" \
  --file package/Dockerfile .
docker push "${BASE_NAME_AMD64}:${CRYPTEIA_VERSION_MAJOR}"
docker push "${BASE_NAME_AMD64}:${CRYPTEIA_VERSION}"

./debian/setup-arm64
BASE_NAME_ARM64="ghcr.io/rails-lambda/crypteia-extension-debian-arm64"
docker build \
  --platform linux/arm64 \
  --tag "${BASE_NAME_ARM64}:${CRYPTEIA_VERSION_MAJOR}" \
  --tag "${BASE_NAME_ARM64}:${CRYPTEIA_VERSION}" \
  --file package/Dockerfile .
docker push "${BASE_NAME_ARM64}:${CRYPTEIA_VERSION_MAJOR}"
docker push "${BASE_NAME_ARM64}:${CRYPTEIA_VERSION}"

docker manifest create \
  "ghcr.io/rails-lambda/crypteia-extension-debian:${CRYPTEIA_VERSION_MAJOR}" \
  --amend "${BASE_NAME_AMD64}:${CRYPTEIA_VERSION_MAJOR}" \
  --amend "${BASE_NAME_ARM64}:${CRYPTEIA_VERSION_MAJOR}"
docker manifest push "ghcr.io/rails-lambda/crypteia-extension-debian:${CRYPTEIA_VERSION_MAJOR}"

docker manifest create \
  "ghcr.io/rails-lambda/crypteia-extension-debian:${CRYPTEIA_VERSION}" \
  --amend "${BASE_NAME_AMD64}:${CRYPTEIA_VERSION}" \
  --amend "${BASE_NAME_ARM64}:${CRYPTEIA_VERSION}"
docker manifest push "ghcr.io/rails-lambda/crypteia-extension-debian:${CRYPTEIA_VERSION}"
