FROM scratch
LABEL org.opencontainers.image.source "https://github.com/rails-lambda/crypteia"
LABEL org.opencontainers.image.description "Rust Lambda Extension for any Runtime to preload SSM Parameters as Secure Environment Variables!"
COPY ./package/opt /opt
