FROM alpine
LABEL org.opencontainers.image.source "https://github.com/customink/crypteia"
LABEL org.opencontainers.image.description "Rust Lambda Extension for any Runtime to preload SSM Parameters as Secure Environment Variables!"
COPY ./package/opt /opt
